### ISSUE TITLE
An error occurred while running “Search DEVONthink 3”

### ISSUE THREAD

**Issue by ryan-cine** [thekoc/devonthink-search-launchbar#3]
- Devonthink Version 3.6.1

CAN NOT use the launchbar plugin, which show "An error occurred while running “Search DEVONthink 3”, i can't find or  understand the logs.
Appreciate for the time you spent on this.

![image](https://user-images.githubusercontent.com/36530040/106691517-988ec200-660e-11eb-8e3e-a26196037835.png)

**Comment by astrosheep-zero** [comment]
Hi, sorry for the late reply. Do you still have the problem? If you do, the log can be seen in the "Console.app" application.

You might want to filter them with the keyword "launchbar". And it would be helpful if you could share the result with me.

<img width="1375" alt="Screen Shot 2021-04-25 at 12 17 25 PM" src="https://user-images.githubusercontent.com/15809388/115980570-4d0e0380-a5c0-11eb-97d9-6ec6c83d6519.png">

**Comment by ryan-cine** [comment]
Appreciate for the reply. 

Nowadays it can work, but I don't know how I get it worked or when. Hope it won't appear again.
